# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
#' @noRd
.rcpp_set_all_Logical <- function(x, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_all_Logical`, x, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_all_Integer <- function(x, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_all_Integer`, x, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_all_Numeric <- function(x, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_all_Numeric`, x, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_all_Character <- function(x, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_all_Character`, x, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_all_Complex <- function(x, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_all_Complex`, x, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_all_Raw <- function(x, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_all_Raw`, x, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_2d_Logical <- function(x, ind1, ind2, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_2d_Logical`, x, ind1, ind2, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_3d_Logical <- function(x, ind1, ind2, ind3, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_3d_Logical`, x, ind1, ind2, ind3, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_4d_Logical <- function(x, ind1, ind2, ind3, ind4, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_4d_Logical`, x, ind1, ind2, ind3, ind4, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_5d_Logical <- function(x, ind1, ind2, ind3, ind4, ind5, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_5d_Logical`, x, ind1, ind2, ind3, ind4, ind5, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_6d_Logical <- function(x, ind1, ind2, ind3, ind4, ind5, ind6, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_6d_Logical`, x, ind1, ind2, ind3, ind4, ind5, ind6, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_7d_Logical <- function(x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_7d_Logical`, x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_8d_Logical <- function(x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, ind8, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_8d_Logical`, x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, ind8, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_2d_Integer <- function(x, ind1, ind2, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_2d_Integer`, x, ind1, ind2, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_3d_Integer <- function(x, ind1, ind2, ind3, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_3d_Integer`, x, ind1, ind2, ind3, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_4d_Integer <- function(x, ind1, ind2, ind3, ind4, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_4d_Integer`, x, ind1, ind2, ind3, ind4, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_5d_Integer <- function(x, ind1, ind2, ind3, ind4, ind5, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_5d_Integer`, x, ind1, ind2, ind3, ind4, ind5, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_6d_Integer <- function(x, ind1, ind2, ind3, ind4, ind5, ind6, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_6d_Integer`, x, ind1, ind2, ind3, ind4, ind5, ind6, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_7d_Integer <- function(x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_7d_Integer`, x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_8d_Integer <- function(x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, ind8, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_8d_Integer`, x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, ind8, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_2d_Numeric <- function(x, ind1, ind2, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_2d_Numeric`, x, ind1, ind2, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_3d_Numeric <- function(x, ind1, ind2, ind3, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_3d_Numeric`, x, ind1, ind2, ind3, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_4d_Numeric <- function(x, ind1, ind2, ind3, ind4, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_4d_Numeric`, x, ind1, ind2, ind3, ind4, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_5d_Numeric <- function(x, ind1, ind2, ind3, ind4, ind5, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_5d_Numeric`, x, ind1, ind2, ind3, ind4, ind5, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_6d_Numeric <- function(x, ind1, ind2, ind3, ind4, ind5, ind6, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_6d_Numeric`, x, ind1, ind2, ind3, ind4, ind5, ind6, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_7d_Numeric <- function(x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_7d_Numeric`, x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_8d_Numeric <- function(x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, ind8, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_8d_Numeric`, x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, ind8, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_2d_Character <- function(x, ind1, ind2, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_2d_Character`, x, ind1, ind2, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_3d_Character <- function(x, ind1, ind2, ind3, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_3d_Character`, x, ind1, ind2, ind3, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_4d_Character <- function(x, ind1, ind2, ind3, ind4, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_4d_Character`, x, ind1, ind2, ind3, ind4, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_5d_Character <- function(x, ind1, ind2, ind3, ind4, ind5, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_5d_Character`, x, ind1, ind2, ind3, ind4, ind5, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_6d_Character <- function(x, ind1, ind2, ind3, ind4, ind5, ind6, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_6d_Character`, x, ind1, ind2, ind3, ind4, ind5, ind6, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_7d_Character <- function(x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_7d_Character`, x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_8d_Character <- function(x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, ind8, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_8d_Character`, x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, ind8, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_2d_Complex <- function(x, ind1, ind2, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_2d_Complex`, x, ind1, ind2, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_3d_Complex <- function(x, ind1, ind2, ind3, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_3d_Complex`, x, ind1, ind2, ind3, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_4d_Complex <- function(x, ind1, ind2, ind3, ind4, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_4d_Complex`, x, ind1, ind2, ind3, ind4, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_5d_Complex <- function(x, ind1, ind2, ind3, ind4, ind5, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_5d_Complex`, x, ind1, ind2, ind3, ind4, ind5, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_6d_Complex <- function(x, ind1, ind2, ind3, ind4, ind5, ind6, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_6d_Complex`, x, ind1, ind2, ind3, ind4, ind5, ind6, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_7d_Complex <- function(x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_7d_Complex`, x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_8d_Complex <- function(x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, ind8, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_8d_Complex`, x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, ind8, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_2d_Raw <- function(x, ind1, ind2, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_2d_Raw`, x, ind1, ind2, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_3d_Raw <- function(x, ind1, ind2, ind3, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_3d_Raw`, x, ind1, ind2, ind3, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_4d_Raw <- function(x, ind1, ind2, ind3, ind4, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_4d_Raw`, x, ind1, ind2, ind3, ind4, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_5d_Raw <- function(x, ind1, ind2, ind3, ind4, ind5, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_5d_Raw`, x, ind1, ind2, ind3, ind4, ind5, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_6d_Raw <- function(x, ind1, ind2, ind3, ind4, ind5, ind6, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_6d_Raw`, x, ind1, ind2, ind3, ind4, ind5, ind6, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_7d_Raw <- function(x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_7d_Raw`, x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_8d_Raw <- function(x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, ind8, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_8d_Raw`, x, ind1, ind2, ind3, ind4, ind5, ind6, ind7, ind8, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_2d_8d_Logical <- function(x, out, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_2d_8d_Logical`, x, out, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_2d_8d_Integer <- function(x, out, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_2d_8d_Integer`, x, out, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_2d_8d_Numeric <- function(x, out, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_2d_8d_Numeric`, x, out, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_2d_8d_Character <- function(x, out, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_2d_8d_Character`, x, out, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_2d_8d_Complex <- function(x, out, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_2d_8d_Complex`, x, out, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_2d_8d_Raw <- function(x, out, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_2d_8d_Raw`, x, out, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_rowcol_Logical <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_rowcol_Logical`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_row_Logical <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_row_Logical`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_col_Logical <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_col_Logical`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_Logical <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_Logical`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_rowcol_Integer <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_rowcol_Integer`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_row_Integer <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_row_Integer`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_col_Integer <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_col_Integer`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_Integer <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_Integer`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_rowcol_Numeric <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_rowcol_Numeric`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_row_Numeric <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_row_Numeric`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_col_Numeric <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_col_Numeric`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_Numeric <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_Numeric`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_rowcol_Character <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_rowcol_Character`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_row_Character <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_row_Character`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_col_Character <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_col_Character`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_Character <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_Character`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_rowcol_Complex <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_rowcol_Complex`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_row_Complex <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_row_Complex`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_col_Complex <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_col_Complex`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_Complex <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_Complex`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_rowcol_Raw <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_rowcol_Raw`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_row_Raw <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_row_Raw`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_col_Raw <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_col_Raw`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_Raw <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_Raw`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_vind_64_Logical <- function(x, ind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_vind_64_Logical`, x, ind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_vind_32_Logical <- function(x, ind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_vind_32_Logical`, x, ind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_vind_64_Integer <- function(x, ind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_vind_64_Integer`, x, ind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_vind_32_Integer <- function(x, ind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_vind_32_Integer`, x, ind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_vind_64_Numeric <- function(x, ind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_vind_64_Numeric`, x, ind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_vind_32_Numeric <- function(x, ind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_vind_32_Numeric`, x, ind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_vind_64_Character <- function(x, ind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_vind_64_Character`, x, ind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_vind_32_Character <- function(x, ind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_vind_32_Character`, x, ind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_vind_64_Complex <- function(x, ind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_vind_64_Complex`, x, ind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_vind_32_Complex <- function(x, ind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_vind_32_Complex`, x, ind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_vind_64_Raw <- function(x, ind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_vind_64_Raw`, x, ind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_vind_32_Raw <- function(x, ind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_vind_32_Raw`, x, ind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Logical <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_col_Logical`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Logical <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_row_Logical`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Integer <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_col_Integer`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Integer <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_row_Integer`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Numeric <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_col_Numeric`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Numeric <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_row_Numeric`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Character <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_col_Character`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Character <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_row_Character`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Complex <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_col_Complex`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Complex <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_row_Complex`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Raw <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_col_Raw`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Raw <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_row_Raw`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_safe_Complex <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_safe_Complex`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_fast_Complex <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_fast_Complex`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_safe_Logical <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_safe_Logical`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_fast_Logical <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_fast_Logical`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_safe_Integer <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_safe_Integer`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_fast_Integer <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_fast_Integer`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_safe_Numeric <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_safe_Numeric`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_fast_Numeric <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_fast_Numeric`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_safe_Character <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_safe_Character`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_fast_Character <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_fast_Character`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_safe_Raw <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_safe_Raw`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_fast_Raw <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_fast_Raw`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_x_Logical <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slcseq_x_Logical`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_set_Logical <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slcseq_set_Logical`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_xrev_Logical <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slcseq_xrev_Logical`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_setrev_Logical <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_range_slcseq_setrev_Logical`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_rm_Logical <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slcseq_rm_Logical`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_setinv_Logical <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slcseq_setinv_Logical`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_x_Integer <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slcseq_x_Integer`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_set_Integer <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slcseq_set_Integer`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_xrev_Integer <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slcseq_xrev_Integer`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_setrev_Integer <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_range_slcseq_setrev_Integer`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_rm_Integer <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slcseq_rm_Integer`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_setinv_Integer <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slcseq_setinv_Integer`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_x_Numeric <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slcseq_x_Numeric`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_set_Numeric <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slcseq_set_Numeric`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_xrev_Numeric <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slcseq_xrev_Numeric`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_setrev_Numeric <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_range_slcseq_setrev_Numeric`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_rm_Numeric <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slcseq_rm_Numeric`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_setinv_Numeric <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slcseq_setinv_Numeric`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_x_Character <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slcseq_x_Character`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_set_Character <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slcseq_set_Character`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_xrev_Character <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slcseq_xrev_Character`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_setrev_Character <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_range_slcseq_setrev_Character`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_rm_Character <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slcseq_rm_Character`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_setinv_Character <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slcseq_setinv_Character`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_x_Complex <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slcseq_x_Complex`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_set_Complex <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slcseq_set_Complex`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_xrev_Complex <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slcseq_xrev_Complex`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_setrev_Complex <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_range_slcseq_setrev_Complex`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_rm_Complex <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slcseq_rm_Complex`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_setinv_Complex <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slcseq_setinv_Complex`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_x_Raw <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slcseq_x_Raw`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_set_Raw <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slcseq_set_Raw`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_xrev_Raw <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slcseq_xrev_Raw`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_setrev_Raw <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_range_slcseq_setrev_Raw`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_rm_Raw <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slcseq_rm_Raw`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slcseq_setinv_Raw <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slcseq_setinv_Raw`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slice_x_Logical <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slice_x_Logical`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slice_set_Logical <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slice_set_Logical`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slice_xrev_Logical <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slice_xrev_Logical`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slice_setrev_Logical <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_range_slice_setrev_Logical`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slice_rm_Logical <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slice_rm_Logical`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slice_setinv_Logical <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slice_setinv_Logical`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slice_x_Integer <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slice_x_Integer`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slice_set_Integer <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slice_set_Integer`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slice_xrev_Integer <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slice_xrev_Integer`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slice_setrev_Integer <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_range_slice_setrev_Integer`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slice_rm_Integer <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slice_rm_Integer`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slice_setinv_Integer <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slice_setinv_Integer`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slice_x_Numeric <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slice_x_Numeric`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slice_set_Numeric <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slice_set_Numeric`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slice_xrev_Numeric <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slice_xrev_Numeric`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slice_setrev_Numeric <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_range_slice_setrev_Numeric`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slice_rm_Numeric <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slice_rm_Numeric`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slice_setinv_Numeric <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slice_setinv_Numeric`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slice_x_Character <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slice_x_Character`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slice_set_Character <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slice_set_Character`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slice_xrev_Character <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slice_xrev_Character`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slice_setrev_Character <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_range_slice_setrev_Character`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slice_rm_Character <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slice_rm_Character`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slice_setinv_Character <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slice_setinv_Character`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slice_x_Complex <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slice_x_Complex`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slice_set_Complex <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slice_set_Complex`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slice_xrev_Complex <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slice_xrev_Complex`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slice_setrev_Complex <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_range_slice_setrev_Complex`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slice_rm_Complex <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slice_rm_Complex`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slice_setinv_Complex <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slice_setinv_Complex`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slice_x_Raw <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slice_x_Raw`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slice_set_Raw <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slice_set_Raw`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slice_xrev_Raw <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slice_xrev_Raw`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slice_setrev_Raw <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_range_slice_setrev_Raw`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slice_rm_Raw <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slice_rm_Raw`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slice_setinv_Raw <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slice_setinv_Raw`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.C_sub2ind_2d_32 <- function(ind1, ind2, dimcumprod) {
    .Call(`_squarebrackets_C_sub2ind_2d_32`, ind1, ind2, dimcumprod)
}

#' @keywords internal
#' @noRd
.C_sub2ind_3d_32 <- function(ind1, ind2, ind3, dimcumprod) {
    .Call(`_squarebrackets_C_sub2ind_3d_32`, ind1, ind2, ind3, dimcumprod)
}

#' @keywords internal
#' @noRd
.C_sub2ind_4d_32 <- function(ind1, ind2, ind3, ind4, dimcumprod) {
    .Call(`_squarebrackets_C_sub2ind_4d_32`, ind1, ind2, ind3, ind4, dimcumprod)
}

#' @keywords internal
#' @noRd
.C_sub2ind_5d_32 <- function(ind1, ind2, ind3, ind4, ind5, dimcumprod) {
    .Call(`_squarebrackets_C_sub2ind_5d_32`, ind1, ind2, ind3, ind4, ind5, dimcumprod)
}

#' @keywords internal
#' @noRd
.C_sub2ind_6d_32 <- function(ind1, ind2, ind3, ind4, ind5, ind6, dimcumprod) {
    .Call(`_squarebrackets_C_sub2ind_6d_32`, ind1, ind2, ind3, ind4, ind5, ind6, dimcumprod)
}

#' @keywords internal
#' @noRd
.C_sub2ind_7d_32 <- function(ind1, ind2, ind3, ind4, ind5, ind6, ind7, dimcumprod) {
    .Call(`_squarebrackets_C_sub2ind_7d_32`, ind1, ind2, ind3, ind4, ind5, ind6, ind7, dimcumprod)
}

#' @keywords internal
#' @noRd
.C_sub2ind_8d_32 <- function(ind1, ind2, ind3, ind4, ind5, ind6, ind7, ind8, dimcumprod) {
    .Call(`_squarebrackets_C_sub2ind_8d_32`, ind1, ind2, ind3, ind4, ind5, ind6, ind7, ind8, dimcumprod)
}

#' @keywords internal
#' @noRd
.rcpp_sub2ind_2d_8d_32 <- function(sub, dimcumprod) {
    .Call(`_squarebrackets_rcpp_sub2ind_2d_8d_32`, sub, dimcumprod)
}

#' @keywords internal
#' @noRd
.C_sub2ind_2d_64 <- function(ind1, ind2, dimcumprod) {
    .Call(`_squarebrackets_C_sub2ind_2d_64`, ind1, ind2, dimcumprod)
}

#' @keywords internal
#' @noRd
.C_sub2ind_3d_64 <- function(ind1, ind2, ind3, dimcumprod) {
    .Call(`_squarebrackets_C_sub2ind_3d_64`, ind1, ind2, ind3, dimcumprod)
}

#' @keywords internal
#' @noRd
.C_sub2ind_4d_64 <- function(ind1, ind2, ind3, ind4, dimcumprod) {
    .Call(`_squarebrackets_C_sub2ind_4d_64`, ind1, ind2, ind3, ind4, dimcumprod)
}

#' @keywords internal
#' @noRd
.C_sub2ind_5d_64 <- function(ind1, ind2, ind3, ind4, ind5, dimcumprod) {
    .Call(`_squarebrackets_C_sub2ind_5d_64`, ind1, ind2, ind3, ind4, ind5, dimcumprod)
}

#' @keywords internal
#' @noRd
.C_sub2ind_6d_64 <- function(ind1, ind2, ind3, ind4, ind5, ind6, dimcumprod) {
    .Call(`_squarebrackets_C_sub2ind_6d_64`, ind1, ind2, ind3, ind4, ind5, ind6, dimcumprod)
}

#' @keywords internal
#' @noRd
.C_sub2ind_7d_64 <- function(ind1, ind2, ind3, ind4, ind5, ind6, ind7, dimcumprod) {
    .Call(`_squarebrackets_C_sub2ind_7d_64`, ind1, ind2, ind3, ind4, ind5, ind6, ind7, dimcumprod)
}

#' @keywords internal
#' @noRd
.C_sub2ind_8d_64 <- function(ind1, ind2, ind3, ind4, ind5, ind6, ind7, ind8, dimcumprod) {
    .Call(`_squarebrackets_C_sub2ind_8d_64`, ind1, ind2, ind3, ind4, ind5, ind6, ind7, ind8, dimcumprod)
}

#' @keywords internal
#' @noRd
.rcpp_sub2ind_2d_8d_64 <- function(sub, dimcumprod) {
    .Call(`_squarebrackets_rcpp_sub2ind_2d_8d_64`, sub, dimcumprod)
}

#' @keywords internal
#' @noRd
.rcpp_abind_all_conform_dims <- function(conform_dim, arg_dim, n, along) {
    .Call(`_squarebrackets_rcpp_abind_all_conform_dims`, conform_dim, arg_dim, n, along)
}

#' @keywords internal
#' @noRd
.rcpp_abind_get_maxdims <- function(arg_dim) {
    .Call(`_squarebrackets_rcpp_abind_get_maxdims`, arg_dim)
}

#' @keywords internal
#' @noRd
.rcpp_abind_check_conform_dims <- function(conform_dim, arg_dim, n, along) {
    .Call(`_squarebrackets_rcpp_abind_check_conform_dims`, conform_dim, arg_dim, n, along)
}

#' @keywords internal
#' @noRd
.rcpp_abind_get_dimnames <- function(x, along) {
    .Call(`_squarebrackets_rcpp_abind_get_dimnames`, x, along)
}

#' @keywords internal
#' @noRd
.rcpp_address <- function(x) {
    .Call(`_squarebrackets_rcpp_address`, x)
}

#' @keywords internal
#' @noRd
.rcpp_list_bindings <- function(ref_address, env, ls) {
    .Call(`_squarebrackets_rcpp_list_bindings`, ref_address, env, ls)
}

#' @keywords internal
#' @noRd
.rcpp_all_addresses <- function(env, ls) {
    .Call(`_squarebrackets_rcpp_all_addresses`, env, ls)
}

#' @keywords internal
#' @noRd
.rcpp_address_in_env <- function(ref_address, env, ls) {
    .Call(`_squarebrackets_rcpp_address_in_env`, ref_address, env, ls)
}

#' @keywords internal
#' @noRd
.C_prod_int <- function(x, start, end) {
    .Call(`_squarebrackets_C_prod_int`, x, start, end)
}

#' @keywords internal
#' @noRd
.C_pre_coord2ind <- function(ind, coord, myprod) {
    invisible(.Call(`_squarebrackets_C_pre_coord2ind`, ind, coord, myprod))
}

#' @keywords internal
#' @noRd
.rcpp_coord2ind <- function(ind, coord, xdim) {
    .Call(`_squarebrackets_rcpp_coord2ind`, ind, coord, xdim)
}

#' @keywords internal
#' @noRd
.rcpp_seq_mlen <- function(x) {
    .Call(`_squarebrackets_rcpp_seq_mlen`, x)
}

#' @keywords internal
#' @noRd
.rcpp_recycle_seq_mlen <- function(x, y) {
    .Call(`_squarebrackets_rcpp_recycle_seq_mlen`, x, y)
}

#' @keywords internal
#' @noRd
.rcpp_serial <- function(x) {
    .Call(`_squarebrackets_rcpp_serial`, x)
}

#' @keywords internal
#' @noRd
.rcpp_is_ma <- function(x) {
    .Call(`_squarebrackets_rcpp_is_ma`, x)
}

#' @keywords internal
#' @noRd
.rcpp_set_namepointer <- function(nms, ind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_namepointer`, nms, ind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_sub2coord <- function(lst, nrow, ncol, lens, reps_each, reps_whole) {
    .Call(`_squarebrackets_rcpp_sub2coord`, lst, nrow, ncol, lens, reps_each, reps_whole)
}

#' @keywords internal
#' @noRd
.C_sub2ind_setrange64 <- function(out, start, end, each, myprod, rp) {
    invisible(.Call(`_squarebrackets_C_sub2ind_setrange64`, out, start, end, each, myprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_sub2ind_general64 <- function(lst, total, reps_each, reps_whole, xdim, dimcumprod) {
    .Call(`_squarebrackets_rcpp_sub2ind_general64`, lst, total, reps_each, reps_whole, xdim, dimcumprod)
}

#' @keywords internal
#' @noRd
.C_sub2ind_setrange32 <- function(out, start, end, each, myprod, rp) {
    invisible(.Call(`_squarebrackets_C_sub2ind_setrange32`, out, start, end, each, myprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_sub2ind_general32 <- function(lst, total, reps_each, reps_whole, xdim, dimcumprod) {
    .Call(`_squarebrackets_rcpp_sub2ind_general32`, lst, total, reps_each, reps_whole, xdim, dimcumprod)
}

