# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
#' @noRd
.rcpp_set_all_atomic <- function(x, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_all_atomic`, x, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_rowcol_Logical <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_rowcol_Logical`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_row_Logical <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_row_Logical`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_col_Logical <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_col_Logical`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_Logical <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_Logical`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_rowcol_Integer <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_rowcol_Integer`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_row_Integer <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_row_Integer`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_col_Integer <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_col_Integer`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_Integer <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_Integer`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_rowcol_Numeric <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_rowcol_Numeric`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_row_Numeric <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_row_Numeric`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_col_Numeric <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_col_Numeric`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_Numeric <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_Numeric`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_rowcol_Character <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_rowcol_Character`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_row_Character <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_row_Character`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_col_Character <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_col_Character`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_Character <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_Character`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_rowcol_Complex <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_rowcol_Complex`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_row_Complex <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_row_Complex`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_col_Complex <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_col_Complex`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_Complex <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_Complex`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_rowcol_Raw <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_rowcol_Raw`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_row_Raw <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_row_Raw`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_col_Raw <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_col_Raw`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_matrix_Raw <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_matrix_Raw`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_vind_32_atomic <- function(x, ind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_vind_32_atomic`, x, ind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_vind_64_atomic <- function(x, ind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_vind_64_atomic`, x, ind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Logical <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_col_Logical`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Logical <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_row_Logical`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Integer <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_col_Integer`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Integer <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_row_Integer`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Numeric <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_col_Numeric`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Numeric <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_row_Numeric`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Character <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_col_Character`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Character <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_row_Character`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Complex <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_col_Complex`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Complex <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_row_Complex`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Raw <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_col_Raw`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Raw <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_row_Raw`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_slice_x_atomic <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slice_x_atomic`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slice_set_atomic <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slice_set_atomic`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slice_xrev_atomic <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slice_xrev_atomic`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slice_setrev_atomic <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slice_setrev_atomic`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_slice_wo_atomic <- function(x, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slice_wo_atomic`, x, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slice_setinv_atomic <- function(x, rp, start, end, by, len) {
    invisible(.Call(`_squarebrackets_rcpp_slice_setinv_atomic`, x, rp, start, end, by, len))
}

#' @keywords internal
#' @noRd
.rcpp_countv <- function(y, v, na, invert, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_countv`, y, v, na, invert, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_whichv_32 <- function(y, v, na, invert, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_whichv_32`, y, v, na, invert, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slicev_x_atomic <- function(x, y, v, na, invert, start, end, by, len) {
    .Call(`_squarebrackets_rcpp_slicev_x_atomic`, x, y, v, na, invert, start, end, by, len)
}

#' @keywords internal
#' @noRd
.rcpp_slicev_set_atomic <- function(x, y, v, na, invert, start, end, by, len, rp) {
    invisible(.Call(`_squarebrackets_rcpp_slicev_set_atomic`, x, y, v, na, invert, start, end, by, len, rp))
}

#' @keywords internal
#' @noRd
.rcpp_abind_all_conform_dims <- function(conform_dim, arg_dim, n, along) {
    .Call(`_squarebrackets_rcpp_abind_all_conform_dims`, conform_dim, arg_dim, n, along)
}

#' @keywords internal
#' @noRd
.rcpp_abind_get_maxdims <- function(arg_dim) {
    .Call(`_squarebrackets_rcpp_abind_get_maxdims`, arg_dim)
}

#' @keywords internal
#' @noRd
.rcpp_abind_check_conform_dims <- function(conform_dim, arg_dim, n, along) {
    .Call(`_squarebrackets_rcpp_abind_check_conform_dims`, conform_dim, arg_dim, n, along)
}

#' @keywords internal
#' @noRd
.rcpp_abind_get_dimnames <- function(x, along) {
    .Call(`_squarebrackets_rcpp_abind_get_dimnames`, x, along)
}

#' @keywords internal
#' @noRd
.rcpp_rcbind_get_sizes <- function(lst, imargin) {
    .Call(`_squarebrackets_rcpp_rcbind_get_sizes`, lst, imargin)
}

#' @keywords internal
#' @noRd
.rcpp_address <- function(x) {
    .Call(`_squarebrackets_rcpp_address`, x)
}

#' @keywords internal
#' @noRd
.rcpp_list_bindings <- function(ref_address, env, ls) {
    .Call(`_squarebrackets_rcpp_list_bindings`, ref_address, env, ls)
}

#' @keywords internal
#' @noRd
.rcpp_all_addresses <- function(env, ls) {
    .Call(`_squarebrackets_rcpp_all_addresses`, env, ls)
}

#' @keywords internal
#' @noRd
.rcpp_address_in_env <- function(ref_address, env, ls) {
    .Call(`_squarebrackets_rcpp_address_in_env`, ref_address, env, ls)
}

#' @keywords internal
#' @noRd
.C_prod_int <- function(x, start, end) {
    .Call(`_squarebrackets_C_prod_int`, x, start, end)
}

#' @keywords internal
#' @noRd
.C_pre_coord2ind <- function(ind, coord, myprod) {
    invisible(.Call(`_squarebrackets_C_pre_coord2ind`, ind, coord, myprod))
}

#' @keywords internal
#' @noRd
.rcpp_coord2ind <- function(ind, coord, xdim) {
    .Call(`_squarebrackets_rcpp_coord2ind`, ind, coord, xdim)
}

#' @keywords internal
#' @noRd
.rcpp_dt_needcoe <- function(x, col, rp) {
    .Call(`_squarebrackets_rcpp_dt_needcoe`, x, col, rp)
}

#' @keywords internal
#' @noRd
.rcpp_dt_find_name <- function(x, v, dir) {
    .Call(`_squarebrackets_rcpp_dt_find_name`, x, v, dir)
}

#' @keywords internal
#' @noRd
.rcpp_seq_mlen <- function(x) {
    .Call(`_squarebrackets_rcpp_seq_mlen`, x)
}

#' @keywords internal
#' @noRd
.rcpp_recycle_seq_mlen <- function(x, y) {
    .Call(`_squarebrackets_rcpp_recycle_seq_mlen`, x, y)
}

#' @keywords internal
#' @noRd
.rcpp_serial <- function(x) {
    .Call(`_squarebrackets_rcpp_serial`, x)
}

#' @keywords internal
#' @noRd
.rcpp_is_ma <- function(x) {
    .Call(`_squarebrackets_rcpp_is_ma`, x)
}

#' @keywords internal
#' @noRd
.rcpp_set_array_d_atomic <- function(x, sub, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_DTYPEd_atomic`, x, sub, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_array_general_atomic <- function(x, s, xdims, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_array_general_atomic`, x, s, xdims, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_namepointer <- function(nms, ind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_namepointer`, nms, ind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_sub2coord <- function(lst, nrow, ncol, lens, reps_each, reps_whole) {
    .Call(`_squarebrackets_rcpp_sub2coord`, lst, nrow, ncol, lens, reps_each, reps_whole)
}

#' @keywords internal
#' @noRd
.rcpp_sub2ind_d_32 <- function(sub, dimcumprod) {
    .Call(`_squarebrackets_rcpp_sub2ind_d_32`, sub, dimcumprod)
}

#' @keywords internal
#' @noRd
.rcpp_sub2ind_d_64 <- function(sub, dimcumprod) {
    .Call(`_squarebrackets_rcpp_sub2ind_d_64`, sub, dimcumprod)
}

#' @keywords internal
#' @noRd
.C_sub2ind_setrange64 <- function(out, start, end, each, myprod, rp) {
    invisible(.Call(`_squarebrackets_C_sub2ind_setrange64`, out, start, end, each, myprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_sub2ind_general64 <- function(lst, total, reps_each, reps_whole, xdim, dimcumprod) {
    .Call(`_squarebrackets_rcpp_sub2ind_general64`, lst, total, reps_each, reps_whole, xdim, dimcumprod)
}

#' @keywords internal
#' @noRd
.C_sub2ind_setrange32 <- function(out, start, end, each, myprod, rp) {
    invisible(.Call(`_squarebrackets_C_sub2ind_setrange32`, out, start, end, each, myprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_sub2ind_general32 <- function(lst, total, reps_each, reps_whole, xdim, dimcumprod) {
    .Call(`_squarebrackets_rcpp_sub2ind_general32`, lst, total, reps_each, reps_whole, xdim, dimcumprod)
}

