# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
#' @noRd
.rcpp_seq_rec2_plus <- function(inits, n, s, m, form, rev) {
    .Call(`_squarebrackets_rcpp_seq_rec2_plus`, inits, n, s, m, form, rev)
}

#' @keywords internal
#' @noRd
.rcpp_seq_rec2_min <- function(inits, n, s, m, form, rev) {
    .Call(`_squarebrackets_rcpp_seq_rec2_min`, inits, n, s, m, form, rev)
}

#' @keywords internal
#' @noRd
.rcpp_seq_rec2_x <- function(inits, n, s, m, form, rev) {
    .Call(`_squarebrackets_rcpp_seq_rec2_x`, inits, n, s, m, form, rev)
}

#' @keywords internal
#' @noRd
.rcpp_seq_rec2_div <- function(inits, n, s, m, form, rev) {
    .Call(`_squarebrackets_rcpp_seq_rec2_div`, inits, n, s, m, form, rev)
}

#' @keywords internal
#' @noRd
.rcpp_set_3d_Logical <- function(x, ind1, ind2, ind3, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_3d_Logical`, x, ind1, ind2, ind3, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_3d_Integer <- function(x, ind1, ind2, ind3, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_3d_Integer`, x, ind1, ind2, ind3, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_3d_Numeric <- function(x, ind1, ind2, ind3, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_3d_Numeric`, x, ind1, ind2, ind3, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_3d_Character <- function(x, ind1, ind2, ind3, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_3d_Character`, x, ind1, ind2, ind3, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_3d_Complex <- function(x, ind1, ind2, ind3, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_3d_Complex`, x, ind1, ind2, ind3, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_3d_Raw <- function(x, ind1, ind2, ind3, dimcumprod, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_3d_Raw`, x, ind1, ind2, ind3, dimcumprod, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_rowcol_Logical <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_rowcol_Logical`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_rowcol_Logical1 <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_rowcol_Logical1`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_row_Logical <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_row_Logical`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_row_Logical1 <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_row_Logical1`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_col_Logical <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_col_Logical`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_col_Logical1 <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_col_Logical1`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_rowcol_Integer <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_rowcol_Integer`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_rowcol_Integer1 <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_rowcol_Integer1`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_row_Integer <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_row_Integer`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_row_Integer1 <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_row_Integer1`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_col_Integer <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_col_Integer`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_col_Integer1 <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_col_Integer1`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_rowcol_Numeric <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_rowcol_Numeric`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_rowcol_Numeric1 <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_rowcol_Numeric1`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_row_Numeric <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_row_Numeric`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_row_Numeric1 <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_row_Numeric1`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_col_Numeric <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_col_Numeric`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_col_Numeric1 <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_col_Numeric1`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_rowcol_Character <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_rowcol_Character`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_rowcol_Character1 <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_rowcol_Character1`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_row_Character <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_row_Character`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_row_Character1 <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_row_Character1`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_col_Character <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_col_Character`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_col_Character1 <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_col_Character1`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_rowcol_Complex <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_rowcol_Complex`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_rowcol_Complex1 <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_rowcol_Complex1`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_row_Complex <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_row_Complex`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_row_Complex1 <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_row_Complex1`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_col_Complex <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_col_Complex`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_col_Complex1 <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_col_Complex1`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_rowcol_Raw <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_rowcol_Raw`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_rowcol_Raw1 <- function(x, rowind, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_rowcol_Raw1`, x, rowind, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_row_Raw <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_row_Raw`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_row_Raw1 <- function(x, rowind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_row_Raw1`, x, rowind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_col_Raw <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_col_Raw`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_set_col_Raw1 <- function(x, colind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_set_col_Raw1`, x, colind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Logical <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_col_Logical`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Logical <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_row_Logical`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Integer <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_col_Integer`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Integer <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_row_Integer`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Numeric <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_col_Numeric`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Numeric <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_row_Numeric`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Character <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_col_Character`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Character <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_row_Character`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Complex <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_col_Complex`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Complex <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_row_Complex`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_row_Raw <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_col_Raw`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setapply_col_Raw <- function(x, f) {
    invisible(.Call(`_squarebrackets_rcpp_setapply_row_Raw`, x, f))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_safe_Complex <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_safe_Complex`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_fast_Complex <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_fast_Complex`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_safe_Logical <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_safe_Logical`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_fast_Logical <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_fast_Logical`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_safe_Integer <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_safe_Integer`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_fast_Integer <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_fast_Integer`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_safe_Numeric <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_safe_Numeric`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_fast_Numeric <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_fast_Numeric`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_safe_Character <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_safe_Character`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_fast_Character <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_fast_Character`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_safe_Raw <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_safe_Raw`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_setrv_fast_Raw <- function(x, v, rp, invert) {
    invisible(.Call(`_squarebrackets_rcpp_setrv_fast_Raw`, x, v, rp, invert))
}

#' @keywords internal
#' @noRd
.rcpp_address <- function(x) {
    .Call(`_squarebrackets_rcpp_address`, x)
}

#' @keywords internal
#' @noRd
.rcpp_list_bindings <- function(ref_address, env, ls) {
    .Call(`_squarebrackets_rcpp_list_bindings`, ref_address, env, ls)
}

#' @keywords internal
#' @noRd
.rcpp_all_addresses <- function(env, ls) {
    .Call(`_squarebrackets_rcpp_all_addresses`, env, ls)
}

#' @keywords internal
#' @noRd
.rcpp_address_in_env <- function(ref_address, env, ls) {
    .Call(`_squarebrackets_rcpp_address_in_env`, ref_address, env, ls)
}

#' @keywords internal
#' @noRd
.rcpp_anybad <- function(indx, value) {
    .Call(`_squarebrackets_rcpp_anybad`, indx, value)
}

#' @keywords internal
#' @noRd
.rcpp_check_conform_dims <- function(conform_dim, arg_dim, n, along) {
    invisible(.Call(`_squarebrackets_rcpp_check_conform_dims`, conform_dim, arg_dim, n, along))
}

#' @keywords internal
#' @noRd
.rcpp_prod_int <- function(x) {
    .Call(`_squarebrackets_rcpp_prod_int`, x)
}

#' @keywords internal
#' @noRd
.rcpp_pre_coord2ind <- function(ind, coord, myprod) {
    invisible(.Call(`_squarebrackets_rcpp_pre_coord2ind`, ind, coord, myprod))
}

#' @keywords internal
#' @noRd
.rcpp_coord2ind <- function(ind, coord, xdim) {
    .Call(`_squarebrackets_rcpp_coord2ind`, ind, coord, xdim)
}

#' @keywords internal
#' @noRd
.rcpp_sb_str <- function(x, ind) {
    .Call(`_squarebrackets_rcpp_sb_str`, x, ind)
}

#' @keywords internal
#' @noRd
.rcpp_sb_str_rp <- function(x, ind, rp_x, rp_ind) {
    .Call(`_squarebrackets_rcpp_sb_str_rp`, x, ind, rp_x, rp_ind)
}

#' @keywords internal
#' @noRd
.rcpp_seq_mlen <- function(x) {
    .Call(`_squarebrackets_rcpp_mlen`, x)
}

#' @keywords internal
#' @noRd
.rcpp_setvind_Complex <- function(x, ind, rp) {
    invisible(.Call(`_squarebrackets_rcpp_setvind_Complex`, x, ind, rp))
}

#' @keywords internal
#' @noRd
.rcpp_sub2ind_2d <- function(ind1, ind2, dimcumprod) {
    .Call(`_squarebrackets_rcpp_sub2ind_2d`, ind1, ind2, dimcumprod)
}

#' @keywords internal
#' @noRd
.rcpp_sub2ind_3d <- function(ind1, ind2, ind3, dimcumprod) {
    .Call(`_squarebrackets_rcpp_sub2ind_3d`, ind1, ind2, ind3, dimcumprod)
}

#' @keywords internal
#' @noRd
.rcpp_sub2ind_4d <- function(ind1, ind2, ind3, ind4, dimcumprod) {
    .Call(`_squarebrackets_rcpp_sub2ind_4d`, ind1, ind2, ind3, ind4, dimcumprod)
}

#' @keywords internal
#' @noRd
.rcpp_sub2ind_5d <- function(ind1, ind2, ind3, ind4, ind5, dimcumprod) {
    .Call(`_squarebrackets_rcpp_sub2ind_5d`, ind1, ind2, ind3, ind4, ind5, dimcumprod)
}

#' @keywords internal
#' @noRd
.rcpp_sub2ind_general <- function(lst, total, reps_each, reps_whole, xdim, dimcumprod) {
    .Call(`_squarebrackets_rcpp_sub2ind_general`, lst, total, reps_each, reps_whole, xdim, dimcumprod)
}

